In [12]:
import numpy as np

# 난수의 재현을 구현하기 위해서 사용.
np.random.seed(1)

# random으로 ndarray를 생성해보아요!
arr = np.random.randint(0,10,(3,4))
print(arr)

# reshape()은 view를 만들어 내요! (0)
# resize()는 reshape과 다르게 동작해요!
# resize는 numpy가 제공하는 함수이면서 ndarray의 method예요!

arr1 = np.resize(arr,(2,6))
print(arr1)

arr[0,0] = 100

print(arr)
print(arr1)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[[5 8 9 5 0 0]
 [1 7 6 9 2 4]]
[[100   8   9   5]
 [  0   0   1   7]
 [  6   9   2   4]]
[[5 8 9 5 0 0]
 [1 7 6 9 2 4]]


In [14]:
import numpy as np

# 난수의 재현을 구현하기 위해서 사용.
np.random.seed(1)

# random으로 ndarray를 생성해보아요!
arr = np.random.randint(0,10,(3,4))
print(arr)

arr.resize(2,6)
print(arr)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[[5 8 9 5 0 0]
 [1 7 6 9 2 4]]


In [16]:
import numpy as np

# 난수의 재현을 구현하기 위해서 사용.
np.random.seed(1)

# random으로 ndarray를 생성해보아요!
arr = np.random.randint(0,10,(3,4))
print(arr)

arr.resize(2,2)  # 가능. reshape()은 불가능!
print(arr)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[[5 8]
 [9 5]]


In [24]:
# indexing과 slicing에 대해서 알아보아요!

import numpy as np

# ndarray를 하나 생성해요!
arr = np.arange(10,20,1) # 1차원 ndarray를 생성
print(arr)

print(arr[0]) # 10
arr[0] = 100
print(arr)
##########################

# python 배울 때 slicing에 대해서 배웠어요!
my_list1 = [1,2,3,4,5]
my_list2 = my_list1[0:2]
print(my_list1) # [1, 2, 3, 4, 5]
print(my_list2) # [1, 2]
# slicing은 원본의 형태(list형태)를 유지해요!
# python의 list는 slicing을 할때 새로운 list가 생성

# numpy의 ndrray를 slicing하면 View가 만들어져요!
arr = np.arange(0,5,1) # [0 1 2 3 4]
print(arr)
arr1 = arr[0:2] # [0 1]
print(arr1)
arr[0] = 100
print(arr) # [100 1 2 3 4]
print(arr1) # [100 1]



[10 11 12 13 14 15 16 17 18 19]
10
[100  11  12  13  14  15  16  17  18  19]
[1, 2, 3, 4, 5]
[1, 2]
[0 1 2 3 4]
[0 1]
[100   1   2   3   4]
[100   1]


In [29]:
# 2차원 ndarray의 indexing과 slicing
# 1~16까지 정수를 이용해서 4행4열의 2차원 ndarray를 생성하세요!
arr = np.arange(1,17,1).reshape(4,4)
print(arr)
print(arr[1,1])  # 6
print(arr[2,:])  # [ 9 10 11 12]
print(arr[1:3,:])
#  [[ 5  6  7  8]
#  [ 9 10 11 12]]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
6
[ 9 10 11 12]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
# Boolean indexing과 Fancy indexing

# Boolean indexing은 배열의 각 요소의 선택여부를
# True, False로 구성된 Booelan Mask를 이용하여
# indexing하는 방식
# Boolean Mask에서 True로 구성된 요소만 추출하는 indexing 방법
import numpy as np

np.random.seed(1)
arr = np.random.randint(0,10,(10,))
print(arr)

# Boolean indexing을 하려면 Boolean mask가 필요!
# Boolean mask는 indexing하려는 ndarray와 shape이 같아요!
# 단, 그 안의 값은 True, False로 구성되어야 해요!
# mask = np.array([True, False, True, False, True, False, True, False, True, False])
# print(mask)

# print(arr[mask])

# 주어진 ndarray에서 짝수만 추출하세요!

# numpy연산은 list연산과 달라요!
# 실제 수치연산을 수행하고 같은 위치에 있는 것끼리
# 연산을 수행해요. 만약 shape이 다르면
# broadcasting을 이용해서 shape을 맞춰서 연산을 수행해요
# 만약 shape을 맞출 수 없으면 오류예요!

print(arr[(arr % 2) == 0])



[5 8 9 5 0 0 1 7 6 9]
[8 0 0 6]


In [52]:
# Fancy indexing
# ndarray에 index 배열을 전달해서 배열 요소를 참조하는 방식

arr = np.arange(0,12,1).reshape(3,4).copy()

print(arr)
print(arr[2,2]) # 10
print(arr[1,2:3]) # [6]
print(arr[1:2,2]) # [6]
print(arr[1:2,1:2]) # [[5]]

print(arr[:,2])# [2 6 10]

# [2 10]
print(arr[[0,2], 2]) # [ 2 10]

# Fancy indexing의 추가사항 하나만 알아두면 되요!
#
# [[ 0  2]
#  [ 8  10]]
print(arr[np.ix_([0,2], [0,2])])  # [ 0 10]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
10
[6]
[6]
[[5]]
[ 2  6 10]
[ 2 10]
[[ 0  2]
 [ 8 10]]


In [57]:
# ndarray의 생성
# ndarray의 함수 및 속성
# ndarray의 indexing과 slicing
# ndarray의 연산

# 기본적으로 ndarray의 사칙연산은 같은 shape의 ndarray끼리
# 이루어져요! (위치가 같은 놈끼리 연산을 수행해야 하기 때문에)

# 만약 shape이 다르다면 바로 오류를 내지는 않아요!
# 최대한 shape을 맞출려고 노력해요! => broadcasting이 발생

arr = np.arange(1,13,1).reshape(3,4).copy()
print(arr)
print(arr + np.array([1,2,3,4]))

# 결국 대부분의 연산은 같은 shape의 ndarray끼리 이루어져요!

# 행렬곱(이건또 몬가요??)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


In [68]:
# 일반적인 사칙연산 외에 함수형태로 제공되는
# 연산이 있어요!

# 2차원 ndarray하나 생성해서 함수들을 알아보아요!
arr = np.arange(1,7,1).reshape(2,3).copy()
print(arr)

# 합을 구해보아요!
# 이런 연산을 우리가 일반적으로 프로그램에서 하듯이
# 로직을 이용해서 구현하면 (for돌리고 변수선언하고..)
# 너무 느려! => 이런 작업을 빠르게 수행할 필요가 있어요!
print(np.sum(arr))  # 21
print(arr.sum()) # 21
print(np.cumsum(arr)) # [ 1  3  6 10 15 21]
print(np.mean(arr)) # 평균 : 3.5
print(np.max(arr)) # 6
print(np.min(arr)) # 1
print(np.argmax(arr)) # 최대값의 1차원적인 위치값(index값) 5
print(np.argmin(arr)) # 0
print(np.std(arr)) # 1.707825127659933
print(np.sqrt(arr))
# [[1.         1.41421356 1.73205081]
#  [2.         2.23606798 2.44948974]]

[[1 2 3]
 [4 5 6]]
21
21
[ 1  3  6 10 15 21]
3.5
6
1
5
0
1.707825127659933
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [71]:
# Numpy의 모든 집계함수는
# axis를 기준으로 동작해요!
# 만약 이 axis(축)을 지정하지 않으면
# axis는 None으로 간주되고 대상영역이
# 전체 ndarray로 설정되요!

import numpy as np

# 1차원 ndarray를 생성
arr1 = np.array([1,2,3,4,5])
print(arr1.sum())  # 15
print(arr1.sum(axis=0))  # axis는 숫자값이예요! 즉, 숫자로 축을 지정
                         # axis의 값이 0이면 열을 의미(1차원인 경우)
                         # 열 방향으로 더해요!
# print(arr1.sum(axis=1)) 이건 오류



AxisError: axis 1 is out of bounds for array of dimension 1

In [80]:
# 2차원 ndarray를 생성
arr1 = np.array([[1,4,8],
                 [2,5,9],
                 [7,3,6]])
# print(arr1)
# print(arr1.sum()) # 45, axis=None으로 설정
# print(arr1.sum(axis=0)) # [10 12 23]
# print(arr1.sum(axis=1)) # [13 16 16]
# print(arr1.argmax(axis=1)) # [2 2 0]

np.random.seed(1)
arr1 = np.random.randint(0,5,(2,2,3))
print(arr1)

print(arr1.sum(axis=0)) #
# [[3 5 4]
#  [5 4 2]]

[[[3 4 0]
  [1 3 0]]

 [[0 1 4]
  [4 1 2]]]
[[3 5 4]
 [5 4 2]]
