In [ ]:
import tensorflow as tf
# tf.data
# Tensorflow에서 데이터 전용 처리 함수 & 클래스가 모여있는 package
# 대용량의 데이터를 처리할 때, 이런 데이터를 머신러닝의 입력으로 사용할때
# 해당 package안의 함수와 class를 이용하면 좋아요!

In [ ]:
# tf.data package안에 있는 여러개의 함수와 class중 가장 중요한 class는
# Dataset이예요! => 여러개의 데이터를 읽어들이는 파이프라인객체를 생성하기
# 위해 사용해요!
# 아하.. Dataset 자체가 데이터를 가지고 있는게 아니예요!
# 데이터를 가져오는 방법과 규칙을 정의하는 놈이예요!

In [ ]:
# Dataset에 대해서 알아보기 전에
# 먼저 tf.Tensor라는것에 대해서 먼저 알아야 해요!

# tf.Tensor는 Tensorflow에서 데이터를 표현하는 가장 기본적인 자료구조
# 지금까지 외부데이터를 ndarray로 만들어서 Tensorflow Model에 입력으로
# 넣었어요! 그러면 Tensorflow Model내에서는 이 데이터가 Tensor로 변환되서
# 사용되요!
# 앗..그럼 numpy의 ndarray를 기반으로 pandas의 DataFrame을 만들어서
# 사용했듯이 numpy의 ndarray를 기반으로 tf.Tensor를 만들어서 사용하는
# 건가요? 아니예요.. 두개는 완전히 다른거예요! 단, 서로 변환은 가능해요!

# tf.Tensor
# 1. 다차원배열
# 2. 데이터 타입도 존재 (np.float32 => tf.float32)
# 3. 행렬연산을 지원(np.add() -> tf.add())
# 4. GPU 메모리 지원(반대로 ndarray는 CPU 메모리만 사용)
# 5. ndarray로 변환할려면 어떻게 해야 하나요 => numpy()

In [8]:
# tf.Tensor를 생성하는 방법
import numpy as np
import tensorflow as tf

# 1차원 Tensor 생성
# np.array([1,2,3])
tensor1 = tf.constant([1,2,3]) # 1차원 Tensor 생성
# print(tensor1) # tf.Tensor([1 2 3], shape=(3,), dtype=int32)
# print(tensor1.numpy())  # [1 2 3]

# 2차원 Tensor 생성
tensor2 = tf.constant([[1,2], [3,4]])
# print(tensor2)

tensor3 = tf.zeros([2, 3])  # []를 이용해서 shape을 명시
# print(tensor3)

tensor4 = tf.range(0, 10, 2)
# print(tensor4)

tensor5 = tf.random.normal([2,3])
# print(tensor5)

tf.Tensor(
[[ 0.769735   -0.03471581  1.8784995 ]
 [-0.65674573 -0.5106066  -0.8224835 ]], shape=(2, 3), dtype=float32)


In [10]:
# Tensor의 연산
a = tf.constant([[1,2],
                 [3,4]])
b = tf.constant([[5,6],
                 [7,8]])

# print(a + b)
print(tf.add(a,b))

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [13]:
# tf.constant() Tensor를 만들면  read only예요!
# 이렇게 Tensor를 만들면 상수로 만들어져요!

# 그러면 변수처럼 값을 변화시킬 수 있는 Tensor는 어떻게 만드나요?
# Tensorflow에서는 tf.Variable로 제공해요!

a = tf.Variable([1.0, 2.0, 3.0])
print(a)

a.assign([10,20,30])
print(a)

# Tensorflow Model안에 들어가는 데이터는 tf.Tensor로 만들어져서 사용!
# Tensorflow Model안에 W, b, filter.. 이런 변하는 변수는 당연히
# tf.Variable로 만들어져서 사용

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([10., 20., 30.], dtype=float32)>


In [17]:
# tf.data.Dataset
# Dataset 생성에는 총 5가지 방법이 있어요!
# 1. from_tensor_slices()
# 입력데이터의 첫번째 차원을 따라서
# 각 원소별로 하나의 샘플을 만들어
# tf.Tensor로 감싸진 Dataset을 생성해요!
# => 쉽게 말하면, 각 원소를 하나의 데이터 샘플로 만들어서
# => 이 데이터 전체를 하나의 Dataset으로 래핑하는 거예요!
# list혹은 ndarray안의 요소들을 조각내서
# 각 요소를 Tensor로 만들어 차례로 반환하는 Dataset객체를 생성

import tensorflow as tf

# my_list = [1, 2, 3, 4, 5]
# dataset = tf.data.Dataset.from_tensor_slices(my_list)
# for data in dataset:
#     print(data)

x_data = [[1.0, 2.0], 
          [3.0, 4.0], 
          [5.0, 6.0]]
t_data = [0, 1, 0]

dataset = tf.data.Dataset.from_tensor_slices((x_data, t_data))

for data in dataset:
    print(data)

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5., 6.], dtype=float32)>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


In [20]:
# 2. from_tensors()
# 여러개의 sample이 아니라 전체를 하나의 tensor로 만들어요!
# 즉, 데이터 1개짜리 Dataset을 만드는거예요!
# my_list = [1, 2, 3, 4, 5]
my_list = [[1, 2],
           [3, 4]]
dataset = tf.data.Dataset.from_tensors(my_list)

for data in dataset:
    print(data)

# 특성 상 많이 사용되지는 않아요. 기본적인 사용에 제한이 있어요!
# 대신...어떤 특수한 상황에서는 사용하기도 해요!
# 작은 데이터셋을 만들어서 test용으로 사용할 경우.

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [21]:
# 3. from_generator()
# Python의 generator함수를 이용해서
# 이 generator함수가 생산하는 값을 Tensor로 만들어서 사용하는
# Dataset을 만드는 함수
# 여러이유로 유용하기 때문에 많이 사용
# 대용량의 데이터를 처리하기가 용이
# 데이터를 증강시키기 위해서 사용.

def gen():
    for i in range(5):
        yield i * 2

dataset = tf.data.Dataset.from_generator(
    generator=gen,
    output_signature=tf.TensorSpec(shape=(),
                                   dtype=tf.int32)
)

for data in dataset:
    print(data)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


In [23]:
def gen():
    for i in range(5):
        yield (i*2, i+1)   # (0, 1)
                           # (2, 2)
                           # (4, 3)
dataset = tf.data.Dataset.from_generator(
    generator=gen,
    output_signature=(tf.TensorSpec(shape=(),
                                   dtype=tf.int32),
                     tf.TensorSpec(shape=(),
                                   dtype=tf.int32))
)

for data in dataset:
    print(data)

(<tf.Tensor: shape=(), dtype=int32, numpy=0>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=2>)
(<tf.Tensor: shape=(), dtype=int32, numpy=4>, <tf.Tensor: shape=(), dtype=int32, numpy=3>)
(<tf.Tensor: shape=(), dtype=int32, numpy=6>, <tf.Tensor: shape=(), dtype=int32, numpy=4>)
(<tf.Tensor: shape=(), dtype=int32, numpy=8>, <tf.Tensor: shape=(), dtype=int32, numpy=5>)


In [28]:
# list_files()
# Dataset을 만드는 함수
# 파일 경로 목록을 Dataset으로 만들어요!

dataset = \
tf.data.Dataset.list_files('./data/cat_dog_small/train/cats/*.jpg')

i = 0
for data in dataset:
    print(data)
    i += 1
    if i % 5 == 0:
        break


tf.Tensor(b'./data/cat_dog_small/train/cats/cat.451.jpg', shape=(), dtype=string)
tf.Tensor(b'./data/cat_dog_small/train/cats/cat.294.jpg', shape=(), dtype=string)
tf.Tensor(b'./data/cat_dog_small/train/cats/cat.295.jpg', shape=(), dtype=string)
tf.Tensor(b'./data/cat_dog_small/train/cats/cat.536.jpg', shape=(), dtype=string)
tf.Tensor(b'./data/cat_dog_small/train/cats/cat.337.jpg', shape=(), dtype=string)


In [ ]:
# 5. 특수한 목적으로 만들어진 파일을 불러들여서 Dataset을 만들때 사용
#    하는 함수가 있어요!
# tf.data.Dataset.TFRecordDataset()  # TFRecord : Tensorflow에서 사용하는
                                     # 표준 데이터 포맷.

In [ ]:
# 총 5개의 방법으로 Dataset을 생성할 수 있어요!
# Data source로부터 다양한 방법으로 데이터를 읽어들여 
# Tensor로 변환해서 데이터를 제공하는 객체
# from_tensor_slices()
# from_tensors()
# from_generator()
# list_files()
# TFRecordDataset(), 기타등등


In [ ]:
# 결국 Data source로 부터 Tensor를 얻었어요!
# Dataset은 파이프라인이예요! 기능적으로 여러가지것들을 이렇게 얻은
# Tensor에 적용할 수 있어요!
# 어떤 작업을 더 할 수 있나요? 그 작업을 하기 위해서 우리는 어떻게 해야 하나요
# 정해져 있는 함수가 있어요!

In [32]:
# 데이터 처리
# Dataset이 가지고 있는 함수들에 대해서 알아보아요!
# 가장 대표적인 함수가 map()
# 1. map() : 별도의 함수를 Tensor에 적용해서 Tensor를 변화시킬 수 있어요!
def gen():
    for i in range(5):
        yield i * 2

dataset = tf.data.Dataset.from_generator(
    generator=gen,
    output_signature=tf.TensorSpec(shape=(),
                                   dtype=tf.int32)
)

def my_func(x):
    return x * x

dataset = dataset.map(my_func,
                     num_parallel_calls=tf.data.AUTOTUNE)  

for data in dataset:
    print(data)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(36, shape=(), dtype=int32)
tf.Tensor(64, shape=(), dtype=int32)


In [39]:
# 2. batch() : 몇개씩 묶어서 하나의 mini-batch를 만들어요!
def gen():
    for i in range(5):
        yield (i * 2, i + 1)

dataset = tf.data.Dataset.from_generator(
    generator=gen,
    output_signature=tf.TensorSpec(shape=(2,),
                                   dtype=tf.int32)
)

def my_func(x):
    return x * x
    
dataset = dataset.map(my_func).batch(3)

for data in dataset:
    print(data)

tf.Tensor(
[[ 0  1]
 [ 4  4]
 [16  9]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[36 16]
 [64 25]], shape=(2, 2), dtype=int32)


In [40]:
# 3. shuffle()
# 데이터의 순서를 섞을 때 사용(학습용 데이터는 섞어주는게 더 학습이 잘되요!)
# validation하거나 test할때는 데이터를 섞지 않아요!
# buffer_size를 명시해야 해요! buffer_size는 dataset의 크기만큼 
# 잡아주는게 좋아요! 하지만 데이터가 너무 큰 경우 buffer_size를 메모리 부족때문에
# 데이터 크기만큼 설정하기 힘들 수 있어요!
# 이런경우에는 일반적으로 1000으로 설정
def gen():
    for i in range(5):
        yield i * 2

dataset = tf.data.Dataset.from_generator(
    generator=gen,
    output_signature=tf.TensorSpec(shape=(),
                                   dtype=tf.int32)
)

dataset = dataset.shuffle(buffer_size=5)

for data in dataset:
    print(data)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [42]:
# 4. repeat()
# 반복해서 데이터를 추출

def gen():
    for i in range(5):
        yield i * 2

dataset = tf.data.Dataset.from_generator(
    generator=gen,
    output_signature=tf.TensorSpec(shape=(),
                                   dtype=tf.int32)
)

dataset = dataset.repeat(2)

for data in dataset:
    print(data)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
# 5. prefetch()
# GPU학습과 CPU 데이터 준비를 병렬로 처리하도록 해요.
# 학습의 속도를 굉장히 많이 높여줘요!
# buffer_size값은 tf.data.AUTOTUNE 으로 설정
def gen():
    for i in range(5):
        yield i * 2

dataset = tf.data.Dataset.from_generator(
    generator=gen,
    output_signature=tf.TensorSpec(shape=(),
                                   dtype=tf.int32)
)

dataset = dataset.prefetch(buffer_size=tf.data.AUTOTUNE)

for data in dataset:
    print(data)

In [ ]:
# 6. cache()
# 디스크에서 읽은 데이터를 메모리에 cache시켜놓고 다음번 사용할 때
# cache에 있는 데이터를 사용하는 개념.
# 학습의 속도가 굉장히 빨라져요!
# 일단 메모리량에 따라서 달라질 수 있어요!
# 데이터가 epoch마다 변화해야 하는 경우에는 cache사용에 주의
# Augmentation이 적용 안될 수 있어요!


In [ ]:
# 결과적으로 
# dataset은 5가지 방법으로 생성할 수 있구요!
# 6개의 함수를 이용해서 dataset을 활용할 수 있어요!
# 1. map() : 여러번 나올 수 있어요!
# 2. batch()
# 3. shuffle()
# 4. repeat()
# 5. prefetch()
# 6. cache() : 데이터의 흐름에서 가장 먼저 호출되요!
#              map()까지 적용시킨 후
#              shuffle()전에, batch()전에, prefetch()전에 

In [49]:
# 배운내용을 적용해보아요!

my_list = [1,2,3,4,5,6,7,8]

dataset = tf.data.Dataset.from_tensor_slices(my_list)

dataset = (dataset.map(lambda x: x * 2, 
                       num_parallel_calls=tf.data.AUTOTUNE)
           .cache()
           .batch(2)
           .shuffle(buffer_size=8)
           .prefetch(buffer_size=tf.data.AUTOTUNE))

for data in dataset:
    print(data)

tf.Tensor([2 4], shape=(2,), dtype=int32)
tf.Tensor([14 16], shape=(2,), dtype=int32)
tf.Tensor([6 8], shape=(2,), dtype=int32)
tf.Tensor([10 12], shape=(2,), dtype=int32)


In [ ]:
# 여기까지 tf.data.Dataset에 대해서 알아보았어요! tf.Tensor부터 시작해서
# 여러 함수들에 대해서 살펴보았는데..
# 이제 MNIST예제를 이용해서 ndarray를 이용하지 않고 Dataset을 이용해서
# 우리 model의 입력을 처리해 보아요!
# 기본적으로 csv 파일 하나는 ./data/minst/train.csv로 가지고 있으면 되요!

In [ ]:
# tf.data.Dataset 자체에는 class비율에 맞게 분리해주는 기능을 따로 없어요!
# 초기에 CSV를 읽어서 sklearn이 가지고 있는 기능을 이용해서 데이터 분리한다음
# Dataset으로 생성


In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [54]:
# 1. Raw Data Loading
df = pd.read_csv('./data/mnist/train.csv')
# display(df.head())

# 2. 결측치 없고, 이상치 없고, 
# feature enginnering 할게 없어요!

# 3. 데이터 분리
# feature(독립변수)와 label(종속변수)를 먼저 분리
x_data = df.drop('label', axis=1, inplace=False).values
t_data = df['label'].values

# 학습용과 테스트용으로 분리
x_data_train, x_data_test, t_data_train, t_data_test = \
train_test_split(x_data,
                 t_data,
                 test_size=0.2,
                 stratify=t_data,
                 random_state=42)

x_data_train, x_data_valid, t_data_train, t_data_valid = \
train_test_split(x_data_train,
                 t_data_train,
                 test_size=0.2,
                 stratify=t_data_train,
                 random_state=42)
print(f'train 테이터의 수 : {len(x_data_train)}')
print(f'validation 테이터의 수 : {len(x_data_valid)}')
print(f'test 테이터의 수 : {len(x_data_test)}')

train 테이터의 수 : 26880
validation 테이터의 수 : 6720
test 테이터의 수 : 8400


In [55]:
# Dataset 생성(3개 만들어야 해요. train,validation,test용)

BATCH_SIZE = 64

def make_dataset(x, t, train=False):
    dataset = tf.data.Dataset.from_tensor_slices((x, t))
    dataset = dataset.map(lambda x, t:(tf.cast(x, tf.float32)/255.0, t),
                          num_parallel_calls=tf.data.AUTOTUNE) # 정규화
    dataset = dataset.cache()
    if train:
        dataset = dataset.shuffle(buffer_size=len(x))
    dataset = dataset.batch(BATCH_SIZE)
    dataset = dataset.prefetch(tf.data.AUTOTUNE)
    return dataset

train_dataset = make_dataset(x_data_train,
                             t_data_train,
                             train=True)

validation_dataset = make_dataset(x_data_valid,
                             t_data_valid,
                             train=False)

test_dataset = make_dataset(x_data_test,
                            t_data_test,
                            train=False)


In [58]:
# Model 구성
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Flatten, Dense
from tensorflow.keras.layers import Dropout, BatchNormalization
from tensorflow.keras.layers import Activation
from tensorflow.keras.optimizers import Adam
# callback은 안해요!

inputs = Input(shape=(784,))
x = Flatten()(inputs)
x = Dense(units=64)(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = Dropout(rate=0.3)(x)
x = Dense(units=128)(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = Dropout(rate=0.3)(x)
x = Dense(units=10,
          activation='softmax')(x)

model = Model(inputs=inputs, 
              outputs=x)

model.compile(optimizer=Adam(learning_rate=1e-3),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(train_dataset,
          epochs=10,
          validation_data=validation_dataset,
          verbose=1)

Epoch 1/10
420/420 [==============================] - 7s 11ms/step - loss: 0.6574 - accuracy: 0.7977 - val_loss: 0.2654 - val_accuracy: 0.9201
Epoch 2/10
420/420 [==============================] - 3s 7ms/step - loss: 0.3457 - accuracy: 0.8927 - val_loss: 0.2072 - val_accuracy: 0.9381
Epoch 3/10
420/420 [==============================] - 3s 7ms/step - loss: 0.2820 - accuracy: 0.9135 - val_loss: 0.1764 - val_accuracy: 0.9457
Epoch 4/10
420/420 [==============================] - 3s 6ms/step - loss: 0.2562 - accuracy: 0.9222 - val_loss: 0.1627 - val_accuracy: 0.9484
Epoch 5/10
420/420 [==============================] - 3s 7ms/step - loss: 0.2339 - accuracy: 0.9262 - val_loss: 0.1552 - val_accuracy: 0.9513
Epoch 6/10
420/420 [==============================] - 3s 6ms/step - loss: 0.2100 - accuracy: 0.9331 - val_loss: 0.1458 - val_accuracy: 0.9554
Epoch 7/10
420/420 [==============================] - 2s 6ms/step - loss: 0.1943 - accuracy: 0.9391 - val_loss: 0.1372 - val_accuracy: 0.9577
Epoch