In [17]:
# Attention 연산을 구현해 보아요!
import tensorflow as tf

# 예제 Text
tokens = ["나는", "너를", "사랑해"]

# 숫자로 변경해야 해요 (원래는 vocabulary를 이용해서 해야 해요!)
word_to_index = {word : i for i, word in enumerate(tokens)}
print(word_to_index)

# 숫자의 시퀀스로 변경해야 해요! => [0 1 2]
input_ids = [word_to_index[word] for word in tokens]
print(input_ids)  # [0, 1, 2]

# 입력데이터를 숫자로 표현했어요 이제 Embedding부터 처리해 보아요!
# Embedding처리는 Tensorflow Keras의 Embedding Layer를 이용할꺼예요!
# 입력데이터를 Tensorflow Tensor로 변경
input_tensor = tf.constant(input_ids)
print(input_tensor)

# Embedding Layer
embedding_dim = 4
embedding_layer = tf.keras.layers.Embedding(input_dim=3,
                                            output_dim=embedding_dim)
embeddings = embedding_layer(input_tensor)
print(embeddings.shape) # (3,4)
print(embeddings.numpy())

# Query. Key, Value를 추출하기 위해서 Dense Layer 3개가 필요!
d_model = 4
W_Q = tf.keras.layers.Dense(units=d_model, 
                            use_bias=False)
W_K = tf.keras.layers.Dense(units=d_model, 
                            use_bias=False)
W_V = tf.keras.layers.Dense(units=d_model, 
                            use_bias=False)
Q = W_Q(embeddings)
K = W_K(embeddings)
V = W_V(embeddings)

print("생성된 Query값")
print(Q.numpy())

print("생성된 Key값")
print(K.numpy())

# 여기까지 수행되었으면 우리 문자열("나는 너를 사랑해")에 대해
# Query, Key, Valyue를 구해낼 수 있어요!
# Attention Score를 구할 수 있어요!
d_k = tf.cast(tf.shape(K)[-1], tf.float32)
print(d_k)

scores = tf.matmul(Q, K, transpose_b=True) / tf.math.sqrt(d_k)
print(scores.shape) # (3, 3)

attention_weight = tf.nn.softmax(scores, axis=-1)
print(attention_weight.shape) # (3,3)
print(attention_weight)
# 확률값으로 가중치를 구할 수 있어요!

output = tf.matmul(attention_weight, V)  # (3,4)
# 출력
print(output.numpy())
# [[ 0.00700442 -0.00990888 -0.00798796  0.00591214]
#  [ 0.00704872 -0.00993998 -0.00799204  0.00593827]
#  [ 0.00698272 -0.00989489 -0.0079865   0.00589986]]

{'나는': 0, '너를': 1, '사랑해': 2}
[0, 1, 2]
tf.Tensor([0 1 2], shape=(3,), dtype=int32)
(3, 4)
[[-0.01388765  0.0110577  -0.04579223  0.0290706 ]
 [ 0.04813231  0.00322082  0.02270922 -0.02421128]
 [-0.03761647  0.033173    0.01714828  0.04607561]]
생성된 Query값
[[ 0.04307849  0.01488583 -0.00275136 -0.0100994 ]
 [-0.02117099 -0.03675365 -0.028884   -0.0031258 ]
 [ 0.02383016  0.07355067  0.01558801 -0.02353384]]
생성된 Key값
[[ 0.01335547  0.00848846  0.0086697   0.03153237]
 [ 0.01103843  0.00308377  0.0034877  -0.04483192]
 [-0.01654801 -0.00531078 -0.07561462  0.04874034]]
tf.Tensor(4.0, shape=(), dtype=float32)
(3, 3)
(3, 3)
tf.Tensor(
[[0.33337945 0.33348033 0.33314022]
 [0.33310238 0.33320832 0.3336893 ]
 [0.33345443 0.3336652  0.33288032]], shape=(3, 3), dtype=float32)
[[ 0.00700442 -0.00990888 -0.00798796  0.00591214]
 [ 0.00704872 -0.00993998 -0.00799204  0.00593827]
 [ 0.00698272 -0.00989489 -0.0079865   0.00589986]]
